version: '3.8'
services:
  text-embeddings:
    image: ghcr.io/huggingface/text-embeddings-inference:1.8
    container_name: embedder
    ports:
      - "8080:80"
      
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]

    environment:
      - API_KEY=${API_KEY}

    volumes:
      - /models/Qwen/Qwen3-Embedding-0.6B:/data

    restart: unless-stopped
    command: >
      --model-id /data
      --api-key ${API_KEY}
      --max-batch-tokens 16384
      --auto-truncate