services:
  agents-tool:
    build:
      context: .
      dockerfile: Dockerfile
      shm_size: '6gb'
    container_name: agents-tool
    ports: 
      - '8490:8490'

    env_file:
      - '.agents.env'
    command: ["./entrypoint.sh"]
    restart: unless-stopped